# PyTorch Binary Classification Model Definition
# Generated by model_definition.py

# Model Architecture
# Input -> Linear(20, 128) -> ReLU -> Dropout(0.2) -> Linear(128, 128) -> ReLU -> Dropout(0.2) -> Linear(128, 1) -> Sigmoid -> Output

import torch
import torch.nn as nn
import torch.nn.functional as F

class BinaryClassifier(nn.Module):
    """
    A simple feedforward neural network for binary classification.
    """
    def __init__(self, input_size=20, hidden_size=128, dropout_rate=0.2):
        super(BinaryClassifier, self).__init__()
        self.fc1 = nn.Linear(input_size, hidden_size)
        self.fc2 = nn.Linear(hidden_size, hidden_size)
        self.fc3 = nn.Linear(hidden_size, 1)
        self.dropout = nn.Dropout(dropout_rate)

    def forward(self, x):
        x = F.relu(self.fc1(x))
        x = self.dropout(x)
        x = F.relu(self.fc2(x))
        x = self.dropout(x)
        x = torch.sigmoid(self.fc3(x))
        return x
