import torch
import torch.nn as nn
import torch.nn.functional as F
import uuid

class BinaryClassifier(nn.Module):
    """
    A simple feedforward neural network for binary classification.
    """
    def __init__(self, input_size=10, hidden_size=64, dropout_rate=0.2):
        super(BinaryClassifier, self).__init__()
        self.fc1 = nn.Linear(input_size, hidden_size)
        self.fc2 = nn.Linear(hidden_size, hidden_size)
        self.fc3 = nn.Linear(hidden_size, 1)
        self.dropout = nn.Dropout(dropout_rate)

    def forward(self, x):
        x = F.relu(self.fc1(x))
        x = self.dropout(x)
        x = F.relu(self.fc2(x))
        x = self.dropout(x)
        x = torch.sigmoid(self.fc3(x))
        return x

# Example usage and saving the model definition
if __name__ == "__main__":
    # Create an instance of the model
    model = BinaryClassifier(input_size=20, hidden_size=128)

    # Define a unique filename using a UUID
    unique_filename = f"binary_classifier_model_{str(uuid.uuid4())[:8]}.py"

    # Save the model definition (this entire script) to the new file
    with open(unique_filename, 'w') as f:
        f.write('# PyTorch Binary Classification Model Definition\n')
        f.write('# Generated by model_definition.py\n\n')
        f.write('# Model Architecture\n')
        f.write('# Input -> Linear(20, 128) -> ReLU -> Dropout(0.2) -> Linear(128, 128) -> ReLU -> Dropout(0.2) -> Linear(128, 1) -> Sigmoid -> Output\n\n')
        f.write('import torch\nimport torch.nn as nn\nimport torch.nn.functional as F\n\n')
        f.write(f"class BinaryClassifier(nn.Module):\n    \"\"\"\n    A simple feedforward neural network for binary classification.\n    \"\"\"\n    def __init__(self, input_size=20, hidden_size=128, dropout_rate=0.2):\n        super(BinaryClassifier, self).__init__()\n        self.fc1 = nn.Linear(input_size, hidden_size)\n        self.fc2 = nn.Linear(hidden_size, hidden_size)\n        self.fc3 = nn.Linear(hidden_size, 1)\n        self.dropout = nn.Dropout(dropout_rate)\n\n    def forward(self, x):\n        x = F.relu(self.fc1(x))\n        x = self.dropout(x)\n        x = F.relu(self.fc2(x))\n        x = self.dropout(x)\n        x = torch.sigmoid(self.fc3(x))\n        return x\n")

    print(f"Model definition saved to {unique_filename}")
