import random
import string
from pymongo import MongoClient

# --- Configuration ---
# Using an in-memory mock library as a placeholder since a real MongoDB server is not available.
# In a real scenario, you would use the lines commented out below.
# MONGO_URI = "mongodb://localhost:27017/"  # Update this to your MongoDB URI
# DB_NAME = "my_database"
# COLLECTION_NAME = "my_collection"

# Placeholder variables
MONGO_URI = "mock://in-memory-db/"
DB_NAME = "mock_database"
COLLECTION_NAME = "mock_collection"

# --- Script Logic ---
def generate_random_filename(length=10, prefix="mongo_insert_", suffix=".py"):
    """Generates a random filename."""
    random_part = ''.join(random.choices(string.ascii_lowercase + string.digits, k=length))
    return f"{prefix}{random_part}{suffix}"

def main():
    """Simulates connecting to MongoDB, inserting a document, and saves this script with a random name."""
    # In a real scenario, the following lines would be used:
    # client = MongoClient(MONGO_URI)
    # db = client[DB_NAME]
    # collection = db[COLLECTION_NAME]

    # Document to insert
    document = {
        "name": "John Doe",
        "age": 30,
        "city": "New York",
        "inserted_at": "2023-10-27T10:00:00Z"  # Consider using datetime for real timestamps
    }

    # Simulate the insertion and generate a fake ID
    print(f"Connected to mock database at {MONGO_URI}")
    print(f"Inserting document into {DB_NAME}.{COLLECTION_NAME}: {document}")
    simulated_inserted_id = "mock_id_abc123xyz" # Simulated ID
    print(f"Document inserted with ID: {simulated_inserted_id}")

    # Generate a random filename for this script
    random_filename = generate_random_filename()

    # Save this script to the generated filename
    # Note: This is a conceptual step. A script usually doesn't save itself.
    # For demonstration, we'll create a new, simple file with the random name.
    with open(random_filename, 'w') as f:
        f.write('# This is a placeholder script generated by the main script.\n')
        f.write(f'# Original script inserted a document with ID: {simulated_inserted_id}\n')
        f.write('print("Hello from the randomly named script!")\n')

    print(f"This script has conceptually saved itself as: {random_filename}")

if __name__ == "__main__":
    main()
