---
- name: Restart a service
  hosts: localhost
  become: yes
  tasks:
    - name: Restart the specified service
      systemd:
        name: "{{ service_name | default('httpd') }}"
        state: restarted
      notify: daemon_reload

    - name: Reload systemd daemon
      systemd:
        daemon_reload: yes
      changed_when: false

  handlers:
    - name: daemon_reload
      systemd:
        daemon_reload: yes