import requests
from bs4 import BeautifulSoup
import random
import string

def scrape_page_title(url):
    """Scrapes the title from a given URL."""
    try:
        response = requests.get(url)
        response.raise_for_status()  # Raise an exception for bad status codes
        soup = BeautifulSoup(response.text, 'html.parser')
        title_tag = soup.find('title')
        if title_tag:
            return title_tag.get_text().strip()
        else:
            return "No title found"
    except requests.exceptions.RequestException as e:
        print(f"Error fetching {url}: {e}")
        return None

def generate_random_filename(extension=".py"):
    """Generates a random filename with the given extension."""
    random_string = ''.join(random.choices(string.ascii_lowercase + string.digits, k=10))
    return f"scraped_titles_{random_string}{extension}"

if __name__ == "__main__":
    # Example URL to scrape
    url_to_scrape = "https://www.python.org" # A reliable test page with an HTML structure
    
    title = scrape_page_title(url_to_scrape)
    
    if title:
        print(f"Scraped title: {title}")
        
        # Generate a random filename
        filename = generate_random_filename()
        print(f"Saving script to: {filename}")
        
        # Write the script itself to the random filename
        with open(filename, 'w') as f:
            f.write('#!/usr/bin/env python3\n')
            f.write('# This script was generated by another script to scrape page titles.\n\n')
            f.write('import requests\n')
            f.write('from bs4 import BeautifulSoup\n\n')
            f.write(f'def scrape_page_title(url):\n')
            f.write(f'    """Scrapes the title from a given URL."""\n')
            f.write(f'    try:\n')
            f.write(f'        response = requests.get(url)\n')
            f.write(f'        response.raise_for_status()\n')
            f.write(f'        soup = BeautifulSoup(response.text, \'html.parser\')\n')
            f.write(f'        title_tag = soup.find(\'title\')\n')
            f.write(f'        if title_tag:\n')
            f.write(f'            return title_tag.get_text().strip()\n')
            f.write(f'        else:\n')
            f.write(f'            return "No title found"\n')
            f.write(f'    except requests.exceptions.RequestException as e:\n')
            f.write(f'        print(f"Error fetching {{url}}: {{e}}")\n')
            f.write(f'        return None\n\n')
            f.write(f'# Example usage\n')
            f.write(f'url_to_scrape = "{url_to_scrape}" # A test page that usually has an HTML structure\n')
            f.write(f'title = scrape_page_title(url_to_scrape)\n')
            f.write(f'if title:\n')
            f.write(f'    print(f"Scraped title: {{title}}")\n')
            f.write(f'else:\n')
            f.write(f'    print("Failed to scrape title")\n')

        print(f"Script saved successfully to {filename}!")
    else:
        print("Failed to scrape title")
