#!/usr/bin/env python3
# This script was generated by another script to scrape page titles.

import requests
from bs4 import BeautifulSoup

def scrape_page_title(url):
    """Scrapes the title from a given URL."""
    try:
        response = requests.get(url)
        response.raise_for_status()
        soup = BeautifulSoup(response.text, 'html.parser')
        title_tag = soup.find('title')
        if title_tag:
            return title_tag.get_text().strip()
        else:
            return "No title found"
    except requests.exceptions.RequestException as e:
        print(f"Error fetching {url}: {e}")
        return None

# Example usage
url_to_scrape = "https://www.python.org" # A test page that usually has an HTML structure
title = scrape_page_title(url_to_scrape)
if title:
    print(f"Scraped title: {title}")
else:
    print("Failed to scrape title")
